export const COPY_CATALOG = {
  nav: {
    brand: 'SOUQ',
    statusPill: 'STATUS: PRE-LAUNCH',
    actionButton: 'Request Access',
  },
  hero: {
    badge: 'AUTUMN 2026 // LIMITED INVITATIONAL COHORTS',
    headline: 'Curated Commerce. Uncompromising Quality.',
    body: 'SOUQ connects discerning patrons with India’s most exceptional verified businesses and independent merchants. Experience a marketplace built on trust, elegance, and zero noise.',
    primaryCTA: 'Request Early Access',
    secondaryCTA: 'Partner With SOUQ',
    securityNote: '🔒 By invitation only. No spam. Unsubscribe anytime.',
  },
  pillars: {
    sectionTag: 'THE SOUQ STANDARD',
    sectionTitle: 'Engineered for trust.',
    card1: {
      tag: '01 / CURATION',
      title: 'Strictly Vetted Merchants',
      body: 'Every seller on SOUQ passes a multi-point verification process. We eliminate low-quality noise so only authentic craft, products, and services remain.',
    },
    card2: {
      tag: '02 / TRANSPARENCY',
      title: 'Direct Business Connections',
      body: 'Interact with verified local enterprises with total clarity. SOUQ bridges patrons and creators through seamless digital storefronts.',
    },
    card3: {
      tag: '03 / EXCLUSIVITY',
      title: 'Cohort-Based Access',
      body: 'Platform access is released in controlled phases to guarantee optimal service, merchant integrity, and concierge-level experience.',
    },
  },
  merchantSection: {
    badge: 'MERCHANT INVITATIONS OPEN',
    headline: 'Elevate your business footprint.',
    body: 'Are you a verified brand, manufacturer, or local business owner? Join our founding merchant cohort before public rollout.',
    ctaButton: 'Apply for Merchant Access →',
    supportingNote: 'Priority onboarding granted to verified local businesses.',
  },
  footer: {
    copyright: '© 2026 SOUQ ONLINE. ALL RIGHTS RESERVED.',
    domain: 'SOUQONLINE.IN',
    statusMonitor: '● SYSTEM STATUS: ALL INFRASTRUCTURE NOMINAL',
    socialLink: 'INSTAGRAM ↗',
    privacyLink: 'PRIVACY POLICY',
    termsLink: 'TERMS OF ACCESS',
  },
  modal: {
    closeAria: 'Close dialogue',
    tabPatron: 'Patron Access',
    tabMerchant: 'Merchant Application',
    patron: {
      title: 'Join the SOUQ Waitlist',
      description: 'Enter your email to request an inaugural invitation code when Cohort 1 opens.',
      emailLabel: 'Email Address',
      emailPlaceholder: 'name@domain.com',
      submitDefault: 'Request Access',
      submitLoading: 'Encrypting & Registering...',
      successTitle: 'You are on the list.',
      successSubtitle: 'Your access request has been recorded. We have dispatched a confirmation receipt to your inbox.',
      queueBadge: 'QUEUE POSITION: VERIFIED // COHORT 1',
      successShareCTA: 'Share on Instagram',
      successCloseCTA: 'Return to Overview',
    },
    merchant: {
      title: 'Apply as a Merchant Partner',
      description: 'Tell us about your enterprise to receive priority merchant onboarding.',
      businessNameLabel: 'Business / Brand Name',
      businessNamePlaceholder: 'e.g. Apex Artisanal Leather',
      emailLabel: 'Business Email',
      emailPlaceholder: 'founder@brand.com',
      categoryLabel: 'Business Category',
      categoryOptions: [
        { value: '', label: 'Select primary category' },
        { value: 'retail', label: 'Retail & Consumer Goods' },
        { value: 'luxury', label: 'Apparel & Luxury Goods' },
        { value: 'artisanal', label: 'Artisanal & Home Goods' },
        { value: 'services_other', label: 'Professional Services & Other' },
      ],
      submitDefault: 'Submit Application',
      submitLoading: 'Processing Application...',
      successTitle: 'Application Received.',
      successSubtitle: 'Our curation team will review your business credentials. Expect a follow-up email within 48 hours.',
      successCloseCTA: 'Done',
    },
    errors: {
      emptyEmail: 'Please enter your email address.',
      invalidEmail: 'Please enter a valid email address (e.g. name@domain.com).',
      emptyBusinessName: 'Please enter your business or brand name.',
      unselectedCategory: 'Please select a business category.',
      rateLimited: 'Too many requests. Please wait 60 seconds before trying again.',
      networkError: 'Unable to process request right now. Please try again shortly.',
      alreadyRegistered: 'This email is already queued in Cohort 1. Check your inbox for updates.',
    },
  },
} as const;
