export const COPY_CATALOG = {
  nav: {
    brand: 'SOUQ',
    statusPill: 'STATUS: PRE-LAUNCH',
    actionButton: 'Request Early Access',
  },
  hero: {
    badge: 'AUTUMN 2026 // LIMITED INVITATIONAL COHORTS',
    headline: 'Curated Commerce. Uncompromising Quality.',
    body: 'SOUQ connects discerning patrons with India’s most exceptional verified businesses and independent merchants. Experience a marketplace built on trust, elegance, and zero noise.',
    primaryCTA: 'Request Early Access',
    secondaryCTA: 'Become a Merchant Partner',
    securityNote: 'By invitation only. No spam. Unsubscribe anytime.',
  },
  pillars: {
    sectionTag: 'THE SOUQ STANDARD',
    sectionTitle: 'Engineered for trust.',
    card1: {
      tag: '01 / CURATION',
      title: 'Strictly Vetted Merchants',
      body: 'Every seller on SOUQ passes a multi-point verification process. We eliminate low-quality noise so only authentic craft, products, and services remain.',
    },
    card2: {
      tag: '02 / TRANSPARENCY',
      title: 'Direct Business Connections',
      body: 'Interact with verified local enterprises with total clarity. SOUQ bridges patrons and creators through seamless digital storefronts.',
    },
    card3: {
      tag: '03 / EXCLUSIVITY',
      title: 'Cohort-Based Access',
      body: 'Platform access is released in controlled phases to guarantee optimal service, merchant integrity, and concierge-level experience.',
    },
  },
  merchantSection: {
    badge: 'MERCHANT INVITATIONS OPEN',
    headline: 'Elevate your business footprint.',
    body: 'Grow your business with SOUQ. We are partnering with trusted businesses, artisanal brands, and creators before public launch.',
    ctaButton: 'Become a Merchant Partner →',
    supportingNote: 'Priority onboarding granted to verified local businesses.',
  },
  footer: {
    copyright: '© 2026 SOUQ ONLINE. ALL RIGHTS RESERVED.',
    domain: 'SOUQONLINE.IN',
    statusMonitor: '● SYSTEM STATUS: ALL INFRASTRUCTURE NOMINAL',
    socialLink: 'INSTAGRAM ↗',
    privacyLink: 'PRIVACY POLICY',
    termsLink: 'TERMS OF ACCESS',
  },
  modal: {
    closeAria: 'Close dialogue',
    tabPatron: 'Early Access (Customer)',
    tabMerchant: 'Merchant Partner',
    customer: {
      title: 'Get Early Access',
      description: 'Be among the first to experience SOUQ. Request your Early Access Cohort today.',
      mobileLabel: 'Mobile Number',
      mobilePlaceholder: '98765 43210',
      countryCode: '+91',
      submitDefault: 'Request Access',
      submitLoading: 'Generating Cohort Code...',
      successTitle: "You're in.",
      successSubtitle: 'Welcome to the SOUQ Early Access Program.',
      cohortLabel: 'YOUR COHORT CODE',
      cohortNote: "Save this code. We'll contact you on WhatsApp before launch with exclusive updates and launch offers.",
      successCloseCTA: 'Done',
    },
    merchant: {
      title: 'Become a Merchant Partner',
      description: "Grow your business with SOUQ. We're partnering with trusted businesses before launch.",
      brandNameLabel: 'Brand Name',
      brandNamePlaceholder: 'e.g. Apex Artisanal Leather',
      whatsappLabel: 'WhatsApp Number',
      whatsappPlaceholder: '98765 43210',
      emailLabel: 'Email Address',
      emailPlaceholder: 'founder@brand.com',
      submitDefault: 'Submit Application',
      submitLoading: 'Processing Lead...',
      successTitle: 'Thank you for your interest.',
      successSubtitle: 'Our team will review your request and contact you soon.',
      successCloseCTA: 'Done',
    },
    errors: {
      emptyMobile: 'Enter a valid mobile number.',
      invalidMobile: 'Enter a valid 10-digit mobile number.',
      duplicateMobile: 'This number has already requested early access.',
      emptyBrandName: 'Please enter your brand name.',
      invalidBrandName: 'Brand name must be at least 2 characters.',
      emptyEmail: 'Please enter your email address.',
      invalidEmail: 'Please enter a valid email address.',
      networkError: 'Something went wrong. Please try again.',
    },
  },
} as const;
